export const UPDATE_SEARCH_BRICKS = "UPDATE_SEARCH_BRICKS";
export const UPDATE_CURRENT_SEARCH = "UPDATE_CURRENT_SEARCH";
export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY"
export const UPDATE_BRICKS = "UPDATE_BRICKS"